[System]
# Starting level: 1a, 1b, 1c, 1d, 1e, 1f, 1g, 2a, 2b, 2c, 2d, 3, 4
start_level = 1a

[Speech]
use_mic = True
vosk_model = ./models/vosk-model-small-en-us-0.15
listen_seconds = 5

[TTS]
audio_feedback = True
tts_engine = auto
tts_rate = 200
pronunciation_overrides = ./config/pronunciation_overrides.json

[GUI]
gui = True
fullscreen = False
gui_width = 1280
gui_height = 720
